#!/usr/bin/env python3
"""gen_equilibration_compare.py — generate equilibration_compare.tex with COMPUTED curves.

Physics (user spec, 2026-07-08):
  two length scales: mechanical h = 60 km, thermal L = 100 km; relief 3 km on both sides.
  trench side: perfectly elastic plate -> equivalent density is the parabola,
      rho_hat(z) = (k_f w_T / g) * phi(z), integral = water-for-rock mass (closure built in).
  ridge side: plate cooling model, T(z) from the series (50 terms) at t = 100 Myr,
      d_rho_th(z) = rho * alpha * (T_a - T(z)); isostasy fixes its integral.
  central panel: Delta(-sigma_zz)(z) = g * running integral of the density difference;
      both lobes ramp to Delta P_T ~ 68 MPa across the relief, then close at 63 vs 100 km.
Declared distortions: relief interval (0-3 km) drawn x3; density axes broken on the
water-rock blocks (curves to scale at +-200 kg/m3, blocks capped with a break glyph)."""
import numpy as np

# ---- physics ----
RHO, ALPHA, TA, KAPPA, G = 3300.0, 3.0e-5, 1350.0, 1.0e-6, 9.81
RHO_W = 1000.0; DRW = RHO - RHO_W                     # water-rock contrast 2300
L = 100e3; H = 60e3; W = 3e3                          # thermal, mechanical, relief
T_MYR = 100.0; T_SEC = T_MYR * 3.155e13
KF = DRW * G
DP = DRW * G * W                                      # ~67.7 MPa

def T_plate(z):                                       # plate-model temperature, 50 terms
    s = z / L
    for n in range(1, 51):
        s += (2.0 / (n * np.pi)) * np.exp(-(n * np.pi / L) ** 2 * KAPPA * T_SEC) * np.sin(n * np.pi * z / L)
    return TA * np.clip(s, 0, 1)

# thermal density excess of the old column (= what the ridge column lacks), below the relief
z_th = np.linspace(W, L, 300)
drho_th = RHO * ALPHA * (TA - T_plate(z_th - W))      # profile measured below old seafloor
m_th = np.trapz(drho_th, z_th)
drho_th *= (DRW * W) / m_th                           # isostasy: equal mass to the block

# equivalent density parabola over the mechanical plate below the trench relief
z_ps = np.linspace(W, W + H, 200)
zeta = (z_ps - (W + H / 2)) / (H / 2)
rho_ps = (KF * W / G) * 1.5 / H * (1 - zeta ** 2)     # peak ~173 kg/m3, integral = DRW*W

# central lobes: g * running integrals (ramp over relief + closure)
def lobe(zs, dens, sign):
    z = np.concatenate([[0], np.linspace(0, W, 8)[1:], zs])
    d = np.concatenate([[sign * DRW], np.full(7, sign * DRW), -sign * dens])
    p = np.concatenate([[0], np.cumsum(0.5 * (d[1:] + d[:-1]) * np.diff(z))]) * G
    return z, p

z_r, p_r = lobe(z_th, drho_th, +1.0)                  # ridge: +DP then decay to 0 at L
z_t, p_t = lobe(z_ps, rho_ps, -1.0)                   # trench: -DP then close at W+H

# ---- drawing scales & declared distortions ----
def zplot(z):                                         # relief x3, true below; cm, downward
    z = np.asarray(z, float) / 1e3
    return -0.068 * np.where(z <= 3, 3 * z, 9 + (z - 3))
XR = 1.0 / 150.0                                      # density: 1 cm = 150 kg/m3
XC = 1.0 / 60e6                                       # pressure: 1 cm = 60 MPa
BLK = 1.7                                             # capped block width (axis broken)

def coords(xs, ys, step=1):
    pts = list(zip(xs, ys))
    sel = pts[::step]
    if sel[-1] != pts[-1]:
        sel.append(pts[-1])                            # never drop the endpoint
    return " ".join(f"({x:.3f},{y:.3f})" for x, y in sel)

# dipole-glyph centroids (schematic representation, not to scale)
cen_blk = zplot(W / 2)                                # water/rock block centroid (~1.5 km)
cen_ps  = zplot(np.trapz(z_ps * rho_ps, z_ps) / np.trapz(rho_ps, z_ps))
cen_th  = zplot(np.trapz(z_th * drho_th, z_th) / np.trapz(drho_th, z_th))

# curve strings
th_c = coords(-drho_th * XR, zplot(z_th), 8)                       # panel (c), negative side
ps_c = coords(rho_ps * XR, zplot(z_ps), 5)                          # panel (a), positive side
ridge_c = coords(p_r * XC, zplot(z_r), 8)
trench_c = coords(p_t * XC, zplot(z_t), 5)
Y3, Y63, Y100 = zplot(3e3), zplot(63e3), zplot(100e3)
AMP = DP * XC

tex = rf"""%% equilibration_compare.tex — GENERATED by gen_equilibration_compare.py (2026-07-08).
%% Computed curves: plate-model thermal profile (50 terms, 100 Myr, L=100 km), elastic
%% equivalent density parabola (h=60 km), and their exact running integrals. Declared
%% distortions: relief (0-3 km) drawn x3; density axes broken on the water-rock blocks.
\documentclass[tikz,border=8pt]{{standalone}}
\usetikzlibrary{{arrows.meta,patterns,patterns.meta}}
\pagecolor{{white}}
\definecolor{{cboxA}}{{HTML}}{{0072B2}}   % Figure-1 trench blue
\definecolor{{cboxB}}{{HTML}}{{D55E00}}   % Figure-1 ridge orange
\begin{{document}}
\begin{{tikzpicture}}[>=Stealth, font=\small,
  curveA/.style={{very thick, cboxB}},
  curveB/.style={{very thick, cboxA}},
  note/.style={{font=\footnotesize, align=center}},
  depthmark/.style={{dashed, black!55}}]

% faint separators between the three panels (drawn first, behind everything), so each comment reads as
% belonging to its own panel
\draw[black!12, line width=0.4pt] (3.6,1.9) -- (3.6,-4.5);
\draw[black!12, line width=0.4pt] (10.85,1.9) -- (10.85,-4.5);

% ============ (a) trench - isostatic: corrected density difference ============
\begin{{scope}}
  \node[font=\small\bfseries, cboxA, anchor=north] at (0,1.7) {{(a) $\Delta\rho^{{*}}(z)$: trench $-$ isostatic}};
  \draw[->] (-2.2,0.35) -- (2.2,0.35) node[right, font=\footnotesize] {{$\Delta\rho^{{*}}$}};
  \draw[black!45] (0,0.35) -- (0,{Y100 - 0.3:.2f});
  % water-for-rock block (axis broken at the cap)
  \fill[cboxA!25, opacity=0.6] (0,0) rectangle (-{BLK},{Y3:.3f});
  \draw[curveB] (0,0) -- (-{BLK},0) -- (-{BLK},{Y3:.3f}) -- (0,{Y3:.3f});
  \foreach \e in {{0, {Y3:.3f}}} {{
    \draw[white, line width=3.5pt] (-{BLK - 0.42:.2f},\e-0.11) -- (-{BLK - 0.22:.2f},\e+0.11);
    \draw[curveB, thin] (-{BLK - 0.48:.2f},\e-0.11) -- (-{BLK - 0.28:.2f},\e+0.11)
                        (-{BLK - 0.36:.2f},\e-0.11) -- (-{BLK - 0.16:.2f},\e+0.11);
  }}
  \node[note, cboxA, anchor=west] at (-2.2,-1.35)
    {{water for rock:\\$-2300$~kg\,m$^{{-3}}$\\(axis broken)}};
  % elastic equivalent density parabola
  \fill[cboxA!25, opacity=0.6] plot coordinates {{{ps_c}}} -- (0,{Y3:.3f}) -- cycle;
  \draw[curveB] plot coordinates {{{ps_c}}};
  \draw[curveB] (0,{zplot(63e3):.3f}) -- (0,{Y100 - 0.3:.2f});
  \node[note, cboxA, anchor=west] at (0.95,-3.85)
    {{equivalent density\\$\hat\rho=\tau_{{zx,x}}/g$\\elastic parabola,\\peak $\approx$170~kg\,m$^{{-3}}$}};
  \node[note, cboxA, anchor=north] at (0,{Y100 - 0.55:.2f}) {{each column has\\equal corrected mass ($\rho^{{*}}$)}};
  % the dipole, schematically: two equal-mass lobes and the arm between their centroids
  \draw[cboxA, very thick] (0,{cen_blk:.3f}) -- (0,{cen_ps:.3f});
  \fill[cboxA] (0,{cen_blk:.3f}) circle (0.085);
  \fill[cboxA] (0,{cen_ps:.3f}) circle (0.085);
  \draw[cboxA, thin] (-0.72,-2.95) -- (0,{(cen_blk+cen_ps)/2:.3f});
  \node[note, cboxA, anchor=east, font=\scriptsize] at (-0.75,-3.0) {{dipole arm}};
\end{{scope}}

% ============ (b) centre: the topographic pressure anomaly ============
\begin{{scope}}[xshift=7.2cm]
  \node[font=\small\bfseries, align=center, anchor=north] at (0,1.7)
    {{(b) topographic pressure anomaly $\Delta(-\sigma_{{zz}})(z)$,\\relative to the same isostatic column}};
  \draw[->] (-2.5,0.35) -- (2.5,0.35) node[right, font=\footnotesize] {{$\Delta(-\sigma_{{zz}})$}};
  \draw[->] (0,0.35) -- (0,{Y100 - 0.55:.2f}) node[below, font=\footnotesize] {{$z$}};
  % lobes (computed integrals)
  \fill[pattern={{Lines[angle=45,distance=12pt,line width=0.35pt]}}, pattern color=cboxA!55] (0,0) -- (-{AMP:.3f},{Y3:.3f}) -- (-{AMP:.3f},{Y100 - 0.15:.2f}) -- (0,{Y100 - 0.15:.2f}) -- cycle;
  \fill[cboxA!35, opacity=0.35] plot coordinates {{{trench_c}}} -- (0,0) -- cycle;
  \draw[curveB] plot coordinates {{{trench_c}}};
  % lithostatic approximation (dashed): the deficit accumulates across the relief and then
  % NEVER equilibrates --- a vertical line, growing without bound with integration depth
  \draw[cboxA, very thick, densely dashed] (0,0) -- (-{AMP:.3f},{Y3:.3f}) -- (-{AMP:.3f},{Y100 - 0.15:.2f});
  \draw[->, cboxA, very thick, densely dashed] (-{AMP:.3f},{Y100 - 0.15:.2f}) -- (-{AMP:.3f},{Y100 - 0.5:.2f});
  \node[note, cboxA, anchor=east, align=right] at (-{AMP + 0.1:.2f},-6.7)
    {{lithostatic\\approximation,\\no equilibration}};
  \fill[cboxB!45, opacity=0.4] plot coordinates {{{ridge_c}}} -- (0,0) -- cycle;
  \draw[curveA] plot coordinates {{{ridge_c}}};
  % amplitudes: both topographic, set within the relief interval
  \draw[->, thick] (0,{Y3:.3f}) -- (-{AMP:.3f},{Y3:.3f});
  \draw[->, thick] (0,{Y3:.3f}) -- ({AMP:.3f},{Y3:.3f});
  \node[note, cboxA, anchor=south] at (-{AMP + 0.85:.2f},{Y3 - 0.05:.3f}) {{$\Delta P_T=\Delta\rho g w_T$}};
  \node[note, cboxB, anchor=south] at ({AMP + 0.85:.2f},{Y3 - 0.05:.3f}) {{$\Delta P_R=\Delta\rho g w_R$}};
  % areas = forces
  \node[note, cboxA, anchor=east, align=right] at (-1.3,-2.2) {{pressure \textbf{{deficit}}\\relative to $x_I$\\$\Rightarrow$ trench pull\\$\Delta\mathrm{{GPE}}^{{*}}$}};
  \node[note, cboxB, anchor=west, align=left] at (1.1,-2.2) {{pressure \textbf{{excess}}\\relative to $x_I$\\$\Rightarrow$ ridge push\\$\Delta\mathrm{{GPE}}$}};
  % depth ticks

\end{{scope}}

% ============ (c) ridge - isostatic: true density difference ============
\begin{{scope}}[xshift=14.4cm]
  \node[font=\small\bfseries, cboxB, anchor=north] at (0,1.7) {{(c) $\Delta\rho(z)$: ridge $-$ isostatic}};
  \draw[->] (-2.2,0.35) -- (2.2,0.35) node[right, font=\footnotesize] {{$\Delta\rho$}};
  \draw[black!45] (0,0.35) -- (0,{Y100 - 0.3:.2f});
  % rock-for-water block (axis broken at the cap)
  \fill[cboxB!30, opacity=0.7] (0,0) rectangle ({BLK},{Y3:.3f});
  \draw[curveA] (0,0) -- ({BLK},0) -- ({BLK},{Y3:.3f}) -- (0,{Y3:.3f});
  \foreach \e in {{0, {Y3:.3f}}} {{
    \draw[white, line width=3.5pt] ({BLK - 0.42:.2f},\e-0.11) -- ({BLK - 0.22:.2f},\e+0.11);
    \draw[curveA, thin] ({BLK - 0.48:.2f},\e-0.11) -- ({BLK - 0.28:.2f},\e+0.11)
                        ({BLK - 0.36:.2f},\e-0.11) -- ({BLK - 0.16:.2f},\e+0.11);
  }}
  \node[note, cboxB, anchor=east] at (2.2,-1.35)
    {{rock for water:\\$+2300$~kg\,m$^{{-3}}$\\(axis broken)}};
  % plate-model thermal root (computed)
  \fill[cboxB!30, opacity=0.7] plot coordinates {{{th_c}}} -- (0,{Y3:.3f}) -- cycle;
  \draw[curveA] plot coordinates {{{th_c}}};
  \node[note, cboxB, anchor=east] at (-0.75,-3.2)
    {{thermal root:\\plate model,\\100~Myr\\peak $\approx$130~kg\,m$^{{-3}}$}};
  \node[note, cboxB, anchor=north] at (0,{Y100 - 0.55:.2f}) {{each column has\\equal mass ($\rho$)}};
  % the dipole, schematically
  \draw[cboxB, very thick] (0,{cen_blk:.3f}) -- (0,{cen_th:.3f});
  \fill[cboxB] (0,{cen_blk:.3f}) circle (0.085);
  \fill[cboxB] (0,{cen_th:.3f}) circle (0.085);
  \draw[cboxB, thin] (0.72,-2.95) -- (0,{(cen_blk+cen_th)/2:.3f});
  \node[note, cboxB, anchor=west, font=\scriptsize] at (0.75,-3.0) {{dipole arm}};
\end{{scope}}

% ============ shared depth lines, links, declared distortions ============
\draw[depthmark] (-2.2,{Y63:.3f}) -- (9.7,{Y63:.3f});
\node[note, cboxA, anchor=north east] at (6.0,{Y63 - 0.06:.3f})
  {{equilibration complete\\\emph{{within the strong plate}} ($h_m\approx60$~km)}};
\draw[depthmark] (4.7,{Y100:.3f}) -- (16.6,{Y100:.3f});
\node[note, cboxB, anchor=south west, align=left] at (7.5,{Y100 + 0.06:.3f})
  {{compensation depth ($z_c$)\\thermal thickness ($h_t$)\\$z_c=h_t\approx100$~km (schematic)}};
%% density -> pressure link ($g\int_0^z\,d\zeta$ arrows) removed 2026-08-14 (user): better stated in the caption.

\end{{tikzpicture}}
\end{{document}}
"""
open("equilibration_compare.tex", "w").write(tex)
print(f"DP = {DP/1e6:.1f} MPa; equiv peak = {rho_ps.max():.0f}; thermal peak = {drho_th.max():.0f} kg/m3")
print(f"masses: block {DRW*W:.3e}, thermal {np.trapz(drho_th, z_th):.3e}, equiv {np.trapz(rho_ps, z_ps):.3e}")
print("wrote equilibration_compare.tex")
