"""isostatic_column_test.py — how much does the reported trench pull change if the first isostatic column is
ASSUMED lithostatic, as the simple analytic estimate of the paper does?

The analysis always measures ΔGPE* = −(Σzz(x_I) − Σzz(x_T)) from the model's own vertical normal stress on both
columns (deformed-Cauchy lines, x_I = first w = 0).  The analytic picture instead takes the isostatic column to be
lithostatic — in these massless models, a zero σzz perturbation, Σzz(x_I) = 0 — which would give ΔGPE* = Σzz(x_T).
The two differ by Σzz(x_I).  The isostatic column carries no net foundation load (w = 0 ⇒ ∫τzx,x dz = dV/dx = 0), yet the
shear-stress gradient is not pointwise zero there (the finite equivalent density at x_I in the hero figures), so
σzz(z) = −∫τzx,x dz′ has a small internal lobe whose first moment Σzz(x_I) is small but non-zero: isostatic, not
lithostatic.  This script measures that cost on every shipped production model and records it.

Per model:  x_I;  Σzz(x_I) [TN/m];  ΔGPE* as measured;  ΔGPE* under the lithostatic-x_I assumption;  the change (%);
the net equivalent-density charge at x_I expressed as an equivalent deflection (∫τzx,x dz / Δρg, ≈ 0 — the column IS
isostatic);  and the peak |σzz| on the x_I column [MPa] (the internal lobe — the column is NOT pointwise lithostatic).

    python analysis/isostatic_column_test.py          # prints the table, writes data/ISOSTATIC_COLUMN.md
"""
import glob, os, sys
import numpy as np
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
from gpe_analysis import Model, reference_lines, trench_ref_km, deformed_shear_gradient

SUITES = ["suite1_strength", "suite2_load", "suite3_background", "suite4_thickness"]
RHO_A, RHO_W, G = 3300.0, 1000.0, 9.81
DRHOG = (RHO_A - RHO_W) * G
OUT = "data/ISOSTATIC_COLUMN.md"


def measure(mdir):
    m = Model(mdir)
    x_t = trench_ref_km(m); x_i = reference_lines(m)["isostatic"]
    Szz_t, _ = m.deformed_resultants(x_t)
    Szz_i, _ = m.deformed_resultants(x_i)
    dG = -(Szz_i - Szz_t)                      # the reported pull (model σzz on both columns)
    dG_lith = Szz_t                            # x_I assumed lithostatic: Σzz(x_I) → 0
    L, tau = deformed_shear_gradient(m, x_i)   # τzx,x on the deformed x_I line
    net_w = np.trapz(tau, L["z"]) / DRHOG      # net charge as an equivalent deflection [m] (≈ 0 at an isostatic column)
    Li = m.deformed_line(x_i)
    return dict(model=os.path.basename(mdir.rstrip("/")), h_km=m.H / 1e3, x_i=x_i, Szz_i=Szz_i / 1e12, dG=dG / 1e12,
                dG_lith=dG_lith / 1e12, change_pct=100 * (dG_lith - dG) / dG, net_w_m=net_w,
                peak_szz_MPa=float(np.nanmax(np.abs(Li["szz"]))) / 1e6)


def main():
    rows = []
    for suite in SUITES:
        for d in sorted(glob.glob(f"data/{suite}/*/")):
            if os.path.isfile(os.path.join(d, "gpe_model.vtu")):
                r = measure(d.rstrip("/")); r["suite"] = suite; rows.append(r)
    hdr = ("| suite | model | h [km] | x_I [km] | Σzz(x_I) [TN/m] | ΔGPE* measured [TN/m] | ΔGPE* if x_I lithostatic [TN/m] "
           "| change [%] | net charge at x_I as deflection [m] | peak \\|σzz\\| on x_I column [MPa] |")
    lines = ["# The isostatic column is isostatic, not lithostatic — cost of the analytic assumption", "",
             "What changes in the reported trench pull if the first isostatic column x_I is ASSUMED lithostatic (Σzz(x_I) = 0, as the",
             "paper's simple analytic estimate does) instead of measured from the model's σzz. Generated by",
             "`python analysis/isostatic_column_test.py` (part of `reproduce.sh`); every shipped production model.", "",
             "- ΔGPE* measured = −(Σzz(x_I) − Σzz(x_T)) on deformed-Cauchy lines, x_I = first w = 0 (the reported quantity).",
             "- ΔGPE* if x_I lithostatic = Σzz(x_T); change = Σzz(x_I) / ΔGPE*.",
             "- Net charge at x_I: ∫τzx,x dz / Δρg — the foundation load the column carries, ≈ 0 (it IS isostatic).",
             "- Peak |σzz| on the x_I column: the internal lobe left by the non-zero shear-stress gradient (it is NOT pointwise lithostatic).", "",
             hdr, "|" + "---|" * 10]
    for r in rows:
        lines.append(f"| {r['suite']} | `{r['model']}` | {r['h_km']:.0f} | {r['x_i']:.1f} | {r['Szz_i']:+.4f} | {r['dG']:.4f} | "
                     f"{r['dG_lith']:.4f} | {r['change_pct']:+.2f} | {r['net_w_m']:+.2f} | {r['peak_szz_MPa']:.2f} |")
    ref = [r for r in rows if r["model"] == "tresca_deep_150_60km_V4" and r["suite"] == "suite1_strength"][0]
    worst = max(rows, key=lambda r: abs(r["change_pct"]))
    s1 = [r for r in rows if r["suite"] == "suite1_strength"]
    lines += ["", f"**Reference model (Tresca, h = 60 km, V = 4 TN/m): {ref['change_pct']:+.2f} %** (Σzz(x_I) = {ref['Szz_i']:+.4f} TN/m). "
              f"Suite 1 range {min(r['change_pct'] for r in s1):+.2f} … {max(r['change_pct'] for r in s1):+.2f} %. "
              f"Largest over all {len(rows)} models: {worst['change_pct']:+.2f} % (`{worst['model']}`)."]
    text = "\n".join(lines) + "\n"
    with open(OUT, "w") as f:
        f.write(text)
    print(text); print("wrote", OUT)


if __name__ == "__main__":
    main()
